version: '3.8'
services:
  docker-desktop-vnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - '6080:80'    # HTTP port
      - '5901:5900'  # VNC port
    volumes:
      - '/dev/shm:/dev/shm'           # Share /dev/shm between the host and container
      - './storage:/root'             # Mount a host directory as a data volume
      - '/swapfile:/swapfile'         # Bind mount the host's swap file
    environment:
      VNC_PASSWORD:  ${VNC_PASSWORD}  # VNC password for authentication
      HTTP_PASSWORD: ${HTTP_PASSWORD}  # HTTP base authentication password
      RESOLUTION:    ${RESOLUTION}    # Fixed screen resolution
      USER:          ${USER}          # Non-root user
      PASSWORD:      ${PASSWORD} # Password for the non-root user
    restart: unless-stopped
